Addresses #12 by adding in a panel with all the Github issues for the…
IllinoisWCS/wcs-display pull request #13
Opened 2016-12-15 08:06 UTC by sskhandek

… site

@kevinwang This works as per the attached screenshot, but I feel like there's a better way to handle refreshing the data than just setting a timeout that goes off every 12 hours. Thoughts?

<img width="813" alt="screen shot 2016-12-15 at 12 06 02 am" src="https://cloud.githubusercontent.com/assets/5349493/21216207/5c9e618a-c25a-11e6-9c75-b514a87d8722.png">

2016-12-15 17:53 UTC, kevinwang requested changes

2016-12-15 17:53 UTC, kevinwang commented on src/panels/githubissues.js
> +        setTimeout(this.updateData, 12 * 60 * 60 * 1000)
Missing semicolon. Additionally, I recommend using `setInterval` to match how the other panels handle polling ([example](https://github.com/IllinoisWCS/wcs-display/blob/master/src/panels/mtd.js#L20)).

2016-12-15 17:53 UTC, kevinwang commented on src/panels/githubissues.js
> +        $.getJSON('https://api.github.com/repos/IllinoisWCS/IllinoisWCS.github.io/issues')
Why is this request duplicated here and in `updateData`? That means the request would be fired twice on mount.

2016-12-15 20:31 UTC, sskhandek commented
@kevinwang made updates. Could you re-check? Thanks!

2016-12-16 02:16 UTC, kevinwang commented
It appears that you have just removed the API call altogether?

2016-12-16 04:05 UTC, sskhandek commented
@kevinwang I'm an idiot. I refactored and I thought I checked, but I didn't run npm build. Putting it back

2016-12-16 04:15 UTC, sskhandek commented
@kevinwang Let's try that again. I put the API call back and I ran the build and it works

2016-12-16 11:52 UTC, kevinwang approved these changes

2016-12-16 15:53 UTC, merged